#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────
#  NovaDesc Installer
# ─────────────────────────────────────────

NOVADESC_DIR="${HOME}/.novadesc"
COMPOSE_FILE="${NOVADESC_DIR}/docker-compose.yml"
ENV_FILE="${NOVADESC_DIR}/.env"
VERSION="0.1.0"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

log()  { echo -e "${GREEN}[NovaDesc]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

check_docker() {
    if ! command -v docker &>/dev/null; then
        warn "Docker not found. Installing..."
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker "$USER"
        log "Docker installed. Please log out and back in, then re-run the installer."
        exit 0
    fi
    if ! docker compose version &>/dev/null; then
        err "Docker Compose v2 not found. Please update Docker Desktop."
    fi
    log "Docker OK"
}

generate_secret() {
    python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null \
        || openssl rand -hex 32
}

configure() {
    mkdir -p "$NOVADESC_DIR"

    if [[ -f "$ENV_FILE" ]]; then
        warn "Existing config found at $ENV_FILE. Skipping configuration."
        return
    fi

    log "Configuring NovaDesc..."

    read -rp "  Admin username [admin]: " ADMIN_USER
    ADMIN_USER="${ADMIN_USER:-admin}"

    read -rsp "  Admin password: " ADMIN_PASS; echo
    [[ -z "$ADMIN_PASS" ]] && err "Password cannot be empty"

    read -rp "  Frontend port [80]: " FRONTEND_PORT
    FRONTEND_PORT="${FRONTEND_PORT:-80}"

    echo ""
    echo "  AI Provider:"
    echo "  1) Ollama (local, recommended for air-gapped networks)"
    echo "  2) Anthropic Claude (requires API key + internet)"
    read -rp "  Choose [1]: " AI_CHOICE
    AI_CHOICE="${AI_CHOICE:-1}"

    AI_PROVIDER="ollama"
    ANTHROPIC_API_KEY=""
    USE_OLLAMA="true"

    if [[ "$AI_CHOICE" == "2" ]]; then
        AI_PROVIDER="anthropic"
        USE_OLLAMA="false"
        read -rsp "  Anthropic API key: " ANTHROPIC_API_KEY; echo
    fi

    SECRET_KEY=$(generate_secret)
    DB_PASS=$(generate_secret | head -c 24)

    cat > "$ENV_FILE" <<EOF
# NovaDesc Configuration — generated by installer
APP_VERSION=${VERSION}

POSTGRES_USER=novadesc
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=novadesc

SECRET_KEY=${SECRET_KEY}
FRONTEND_PORT=${FRONTEND_PORT}

AI_PROVIDER=${AI_PROVIDER}
OLLAMA_MODEL=llama3
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

ADMIN_USER=${ADMIN_USER}
ADMIN_PASS=${ADMIN_PASS}
EOF

    log "Config saved to $ENV_FILE"
}

pull_images() {
    log "Pulling Docker images..."
    docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" pull
}

start() {
    log "Starting NovaDesc..."
    PROFILE_FLAG=""
    # shellcheck disable=SC1090
    source "$ENV_FILE"
    [[ "${AI_PROVIDER:-ollama}" == "ollama" ]] && PROFILE_FLAG="--profile with-ollama"

    # shellcheck disable=SC2086
    docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" $PROFILE_FLAG up -d

    FRONTEND_PORT="${FRONTEND_PORT:-80}"
    log "NovaDesc is running at http://localhost:${FRONTEND_PORT}"
}

main() {
    echo ""
    echo "  ███╗   ██╗ ██████╗ ██╗   ██╗ █████╗ ██████╗ ███████╗███████╗ ██████╗"
    echo "  ████╗  ██║██╔═══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝"
    echo "  ██╔██╗ ██║██║   ██║██║   ██║███████║██║  ██║█████╗  ███████╗██║"
    echo "  ██║╚██╗██║██║   ██║╚██╗ ██╔╝██╔══██║██║  ██║██╔══╝  ╚════██║██║"
    echo "  ██║ ╚████║╚██████╔╝ ╚████╔╝ ██║  ██║██████╔╝███████╗███████║╚██████╗"
    echo "  ╚═╝  ╚═══╝ ╚═════╝   ╚═══╝  ╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝ ╚═════╝"
    echo "  Maintenance & Repair Management System v${VERSION}"
    echo ""

    check_docker
    configure

    cp "$(dirname "$0")/../docker-compose.yml" "$COMPOSE_FILE"

    pull_images
    start
}

main "$@"
